#!/bin/bash

$ERRORSTRING = "Error. Please make sure you've indicated correct parameters"
if [ $# -eq 0 ]
    then
        echo $ERRORSTRING;
elif [ $1 == "live" ]
    then
        mkdir ./dist/downloads
        cp ./downloads/* ./dist/downloads
        if [[ -z $2 ]]
            then
                echo "Running dry-run"
                rsync --dry-run -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./dist/ deployer@liki.es:~/lbn3prev
        elif [ $2 == "go" ]
            then
                echo "Running actual deploy"
                rsync -az --force --delete --progress --exclude-from=rsync_exclude.txt -e "ssh -p22" ./dist/ deployer@liki.es:~/lbn3prev
        else
            echo $ERRORSTRING;
        fi
fi

